### ISSUE TITLE
LUA not recognized by YimMenu

### ISSUE THREAD

**Issue by AKGfra** [YimMenu-Lua/Casino-Pacino#5] opened 2023-12-27 15:11 UTC
Hello
I put your lua script on yim menu folder "LUA" script, but when i inject it (while using the button reload), it does nothing and my game instant crash

I didn't upload the json.lua ... is this the problem? I am the only one who experiment the issue?

Thanks

**Comment by TwystedMind** [comment] 2023-12-27 19:59
In order for this (or any) YimMenu LUA script to work, you need to add **both** the "CasinoPacino.lua" and "JSON.lua" to the YimMenu "scripts" folder.  This folder is located at the path:  
C:\Users\YourProfileName\AppData\Roaming\YimMenu

You can either manually go to this file path and paste the "CasinoPacino.lua" and "JSON.lua" into the "scripts" folder, or after launching and loading into GTA V, inject YimMenu, go to Settings > LUA > Open Scripts Folder, then paste both .lua files there.  Then just click on "Reload All Scripts", and they should be there.  You'll then find the casino options under Network > Casino in YimMenu.

If you have copied the .lua files to anywhere other than the "scripts" folder in YimMenu, delete them to prevent any potential issues.  Also, make sure you are running the latest version of YimMenu (last "Nightly Update" was released 5 days ago).

**Comment by gir489returns** [comment] 2024-01-10 17:23
This is a duplicate of #6

**Closed by gir489returns** 2024-01-10 17:23 UTC
