### ISSUE TITLE
Roulette and Blackjack features don't work

### ISSUE THREAD

**Issue by Rxann** [YimMenu-Lua/Casino-Pacino#8] opened 2024-04-04 20:53 UTC
Probably sig related

**Comment by gir489returns** [comment] 2024-04-04 21:02
Duplicate of #4 also fuck you for not liking my branch names, maybe learn how to use Lua properly.

![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/93cd6787-190d-4cea-92e8-9dafa4380823)
![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/43bfd9e0-8def-453c-b7a0-256530ff12dd)
![image](https://github.com/YimMenu-Lua/Casino-Pacino/assets/100792176/5fdc9284-3ff1-46d3-ba37-be3cc8001f7b)

**Closed by gir489returns** 2024-04-04 21:02 UTC

**Comment by Rxann** [comment] 2024-04-04 22:20
> Duplicate of #4 also fuck you for not liking my branch names, maybe learn how to use Lua properly.
> 
> ![image](https://private-user-images.githubusercontent.com/100792176/319772655-93cd6787-190d-4cea-92e8-9dafa4380823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjkzNjQsIm5iZiI6MTcxMjI2OTA2NCwicGF0aCI6Ii8xMDA3OTIxNzYvMzE5NzcyNjU1LTkzY2Q2Nzg3LTE5MGQtNGNlYS05MmU4LTlkYWZhNDM4MDgyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMjE3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjUyMmRjOGI2NDZjYzU1NjVhMjZjMzczYzgzYzY4ODEzNjA4ZTAyMGYxNTg2ZmE5NGRhY2U0YjBjMmRmMzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F9zxCCHC6tMksVbsEHbh_WExLruLYcgxULZSlvR17-M) ![image](https://private-user-images.githubusercontent.com/100792176/319772911-43bfd9e0-8def-453c-b7a0-256530ff12dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjkzNjQsIm5iZiI6MTcxMjI2OTA2NCwicGF0aCI6Ii8xMDA3OTIxNzYvMzE5NzcyOTExLTQzYmZkOWUwLThkZWYtNDUzYy1iN2EwLTI1NjUzMGZmMTJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMjE3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2ViYmM3ZDgyNWI5ZTI4MDdkZmUxMGE4MjQwMzY4NGEwNGQyOGEzZTU3YTA0MDkxOWJiNzcxNzdkZmI4ZDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IlmtkREoygypUOiddUGP_mNAl6ZNMMiNOqKPzOObQyg) ![image](https://private-user-images.githubusercontent.com/100792176/319773011-5fdc9284-3ff1-46d3-ba37-be3cc8001f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjkzNjQsIm5iZiI6MTcxMjI2OTA2NCwicGF0aCI6Ii8xMDA3OTIxNzYvMzE5NzczMDExLTVmZGM5Mjg0LTNmZjEtNDZkMy1iYTM3LWJlM2NjODAwMWY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQyMjE3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjJmYzVkMTUyOWM3NDU0ODk0Y2ZhNGQwMGRkMGM2YzA3MTZmMjlkZGEzYWQzYTE0NTk4NGQ2ZGM0MGQwM2MyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tF8nmcc92KmjToikQbuqpy35Cl1WGa2jrQ14b91Ix9g)

this is off topic but we have the exact same amount of casino chips. i dont need to learn lua. it seems rather gay to me. when did i not like ur branch names btw

**Comment by gir489returns** [comment] 2024-04-04 23:03
Cope seethe and dilate.
